# Generated by Django 5.2.17 on 2026-09-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='c_number',
            field=models.CharField(max_length=15),
        ),
    ]
