# Generated by Django 5.2.17 on 2026-09-07 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_userprofile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetCertified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('farm_name', models.TextField()),
                ('farm_address', models.TextField()),
                ('farm_type', models.TextField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='core.userprofile')),
            ],
        ),
    ]
