# Generated by Django 5.2.17 on 2026-09-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cart_checkout_id_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_record', to='orders.order'),
        ),
    ]
