# Generated by Django 5.2.17 on 2026-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
