# Generated by Django 5.2.17 on 2026-09-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_farmerproduct_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleRecord',
        ),
    ]
