# Generated by Django 5.2.17 on 2026-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='low_stock_notified',
            field=models.BooleanField(default=False),
        ),
    ]
